image_width: 1600
image_height: 1200
camera_name: basler_left
camera_matrix:
  rows: 3
  cols: 3
  data: [814.70114,   0.     , 801.2499 ,
           0.     , 811.53998, 602.45886,
           0.     ,   0.     ,   1.     ]
distortion_model: rational_polynomial
distortion_coefficients:
  rows: 1
  cols: 8
  data: [0.241211, -0.016032, -0.000218, -0.000019, 0.000808, 0.657622, 0.000000, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [273.43436,   0.     , 800.78099,   0.     ,
           0.     , 272.94934, 598.36864,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
